import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';
import { Fragment } from 'react';


export const getServerSideProps = async () => {
  const floors = await fetch('http://localhost:3000/api/units');
  const distibution = await fetch('http://localhost:3000/api/distribution');
  const transactions = await fetch('http://localhost:3000/api/transactions');
  const dataFloors = await floors.json();
  const dataDistribution = await distibution.json();
  const dataTransactions = await transactions.json();

  return {
    props: {
      floorData: dataFloors,
      distibutionData: dataDistribution,
      transactionsData: dataTransactions
    }
  }
}

export default function Home({ floorData, distibutionData, transactionsData }) {

  const router = useRouter();
  setInterval(() => {
    router.replace(router.asPath);
  }, 30000)


  return (

    < div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3 className="mt-2 mb-3">Available Units</h3>
      <ul className="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li className="nav-item" role="presentation">
          <button className="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-BLK6" type="button" role="tab" aria-controls="pills-home" aria-selected="true">BLK 6</button>
        </li>
        <li className="nav-item" role="presentation">
          <button className="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-BLK8" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">BLK 8</button>
        </li>

      </ul>

      <div className="tab-content" id="pills-tabContent">

        {
          floorData.map((unit, i) => (

            <div key={i} className={unit.unitCode === "BLK6" ? `tab-pane fade show active` : `tab-pane fade show`} id={`pills-${unit.unitCode}`} role="tabpanel" aria-labelledby="pills-home-tab">
              <table className="table table-stripe">
                <thead>
                  <tr>
                    <th></th>
                    <th>#10</th>
                    <th>#11</th>
                    <th>#12</th>
                    <th>#13</th>
                    <th>#14</th>

                  </tr>
                </thead>
                <tbody>
                  {unit.stories.map((story, i) => (
                    <tr key={i}>
                      <td>#36</td>
                      {
                        story.floorData.map((floor, i) => (

                          <td key={i}>
                            <a href={floor.image} target="_blank">
                              {floor.sqft} <br />
                              {floor.bedRooms} <br />
                              <span style={{ color: "red", fontWeight: 500 }}>{floor.availability}</span> <br />
                              {floor.soldDate}
                            </a>
                          </td>

                        ))
                      }

                    </tr>
                  ))
                  }

                </tbody>
              </table>
            </div>
          ))
        }
      </div>

      <h3 className="mt-5 mb-3">Units Distribution</h3>
      <table className="table table-stripe">
        <thead>
          <tr>
            <th>Type</th>
            <th>Name</th>
            <th>Area(sqft)</th>
            <th>Available Units</th>
            <th>Price From</th>
          </tr>
        </thead>
        <tbody>
          {
            distibutionData.map((dis, i) => (
              <Fragment key={i}>
                {dis.distribution.map(xx => (
                  <tr key={xx.name}>
                    <td>{dis.type}</td>
                    <td title="View Plan"><a href={xx.image} target="_blank">{xx.name}</a> </td>
                    <td>{xx.area}</td>
                    <td>{xx.availableUnits}</td>
                    <td>{xx.priceFrom}</td>
                  </tr>
                ))}
              </Fragment>
            ))
          }

        </tbody>
      </table>

      <h3 className="mt-5 mb-3">Transactions</h3>
      <table className="table table-stripe">

        <tbody>
          {
            transactionsData.map((dis, i) => (
              <tr key={i}>
                <td><strong>{dis.date}</strong></td>
                <td>{dis.status}</td>
              </tr>
            ))
          }

        </tbody>
      </table>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
